knpu_oauth2_client:
    clients:
        # configure your clients as described here: https://github.com/knpuniversity/oauth2-client-bundle#configuration
        google:
            type: google
            client_id: '%env(OAUTH_GOOGLE_CLIENT_ID)%'
            client_secret: '%env(OAUTH_GOOGLE_CLIENT_SECRET)%'
            redirect_route: connect_google_check
            redirect_params: {}
        facebook:
            type: facebook
            client_id: '%env(OAUTH_FACEBOOK_CLIENT_ID)%'
            client_secret: '%env(OAUTH_FACEBOOK_CLIENT_SECRET)%'
            redirect_route: connect_facebook_check
            redirect_params: {}
            graph_api_version: v15.0
        apple:
            type: apple
            client_id: '%env(OAUTH_APPLE_CLIENT_ID)%'
            key_file_id: '%env(OAUTH_APPLE_KEY_FILE_ID)%'
            key_file_path: '%env(OAUTH_APPLE_KEY_FILE_PATH)%'
            team_id: '%env(OAUTH_APPLE_TEAM_ID)%'
            redirect_route: connect_apple_check
            redirect_params: {}
