services:
    eventwithme-traefik:
        image: "traefik:latest"
        container_name: "eventwithme-traefik"
        command:
            - "--providers.docker=true"
            - "--providers.docker.exposedByDefault=false"
            - "--providers.docker.network=proxy"
            - "--entrypoints.http.address=:80"
            - "--entrypoints.https.address=:443"
            - "--entrypoints.http.http.redirections.entryPoint.to=https"
            - "--entrypoints.http.http.redirections.entryPoint.scheme=https"
            - "--certificatesresolvers.le.acme.email=admin@eventwithme.com"
            - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
            - "--certificatesresolvers.le.acme.httpChallenge=true"
            - "--certificatesresolvers.le.acme.httpChallenge.entryPoint=http"
            - "--api.dashboard=true"
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
            - "./docker/traefik/acme:/letsencrypt"
        networks:
            - proxy
    eventwithme-memcached:
        container_name: eventwithme-memcached
        image: memcached:alpine
        networks:
            - proxy
    eventwithme-nginx:
        container_name: eventwithme-nginx
        image: nginx:alpine
        working_dir: /application
        depends_on:
            -   eventwithme-php
        volumes:
            - .:/application
            - ./vendor:/application/vendor:delegated
            - ./var:/application/var:delegated
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.eventwithme.rule=Host(`eventwithme.com`)"
            - "traefik.http.routers.eventwithme.entrypoints=https"
            - "traefik.http.routers.eventwithme.tls=true"
            - "traefik.http.routers.eventwithme.tls.certresolver=le"
            - "traefik.http.services.eventwithme.loadbalancer.server.port=80"
        networks:
            - proxy
    eventwithme-php:
        container_name: eventwithme-php
        build:
            context: .
            dockerfile: docker/php-fpm/Dockerfile
            target: prod
        working_dir: /application
        volumes:
            - .:/application
            - ./vendor:/application/vendor:delegated
            - ./var:/application/var:delegated
            - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/8.3/fpm/conf.d/99-overrides.ini
            - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/8.3/cli/conf.d/99-overrides.ini
            - ./docker/php-fpm/opcache.ini:/etc/php/8.3/fpm/conf.d/opcache.ini
        extra_hosts:
            - host.docker.internal:172.17.0.1
        networks:
            - proxy
    eventwithme-rabbitmq:
        image: rabbitmq:3.7-management
        container_name: eventwithme-rabbitmq
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=admin
        volumes:
            - rabbitmq-data:/var/lib/rabbitmq
        networks:
            - proxy
volumes:
    db-data:
    pgadmin-data:
    rabbitmq-data:
networks:
    proxy:
        external: true
