controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    exclude: '../src/Controller/Api/'

api_controllers:
    resource: 
        path: ../src/Controller/Api/
        namespace: App\Controller\Api
    type: attribute
    prefix: /

# API Documentation
app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

# API Documentation in JSON format
app.swagger:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }
